version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: composer
    directory: /apps/backoffice
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
