[package]
name = "sibyl-backend"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "sibyl_backend"
path = "src/lib.rs"

[[bin]]
name = "sibyl-backend"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tower = "0.5.2"
